import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { ExperienceController } from './../src/experience/experience.controller';
import { LlmRouterService, type RoutedGenerationRequest } from './../src/llm/llm-router.service';
import { AppModule } from './../src/app.module';

describe('MVP Smoke Flow (e2e)', () => {
  let app: INestApplication;
  let experienceController: ExperienceController;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(LlmRouterService)
      .useValue({
        generateStructured: jest.fn(async (request: RoutedGenerationRequest) => ({
          provider: request.provider ?? 'openai',
          model: request.qualityMode === 'quality' ? 'gpt-5.4' : 'gpt-5-mini',
          rawText: JSON.stringify({
            title: 'Smoke Test Experience',
            description: 'Generated by mocked LLM router for smoke tests.',
            html: '<main><h1>Smoke Test</h1><p>Interactive preview</p></main>',
            css: 'main{font-family:Arial;padding:8px;}',
            js: 'console.log("smoke-test");',
          }),
        })),
      })
      .compile();

    app = moduleFixture.createNestApplication();
    await app.init();
    experienceController = moduleFixture.get<ExperienceController>(ExperienceController);
  });

  afterEach(async () => {
    await app.close();
  });

  it('prompt -> generate -> refine should succeed', async () => {
    const generateResponse = await experienceController.generate({
      prompt: 'Teach me about photosynthesis with a mini quiz.',
      format: 'quiz',
      audience: 'middle-school',
      qualityMode: 'fast',
    });

    expect(generateResponse.ok).toBe(true);
    expect(generateResponse.data.experience.title).toBeTruthy();

    const refineResponse = await experienceController.refine({
      originalPrompt: 'Teach me about photosynthesis with a mini quiz.',
      refinementInstruction: 'Make it easier for younger students.',
      priorExperience: generateResponse.data.experience,
      qualityMode: 'quality',
    });

    expect(refineResponse.ok).toBe(true);
    expect(refineResponse.data.experience.html).toBeTruthy();
    expect(refineResponse.data.metadata.renderingContract).toEqual({
      iframeOnly: true,
      sandbox: 'allow-scripts',
      networkAccess: 'disallowed',
      externalLibraries: 'disallowed',
    });
  });
});
